# Generated by Django 4.2.18 on 2025-02-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0002_delete_erratum_delete_erratumreference'),
        ('operatingsystems', '0005_rename_osgroup_osrelease_rename_os_osvariant_and_more'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErratumReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('er_type', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Erratum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('e_type', models.CharField(max_length=255)),
                ('issue_date', models.DateTimeField()),
                ('synopsis', models.CharField(max_length=255)),
                ('cves', models.ManyToManyField(blank=True, to='security.cve')),
                ('osreleases', models.ManyToManyField(blank=True, to='operatingsystems.osrelease')),
                ('packages', models.ManyToManyField(blank=True, to='packages.package')),
                ('references', models.ManyToManyField(blank=True, to='errata.erratumreference')),
            ],
            options={
                'verbose_name': 'Erratum',
                'verbose_name_plural': 'Errata',
            },
        ),
    ]
